os: linux
dist: focal
language: python
python:
  - "3.7"

env:
  global:
    - secure: N1OMY1FWUuUYkImKZM/0IMbY4iSX6isuvzK11sbjnfNDrZLOTEy6YVslcjw6jbSXWyG49ffN1AAiINoWgrD6HYO8Gad8AVzZvK3Tm/mC54cqLa+1AeFPiFPm9dLp9p2xeDlyEVw7AZ04xvAv/o5W0DmXkkQ548bQj35d3HWJiY0fK3VzB72vHBp0WVAv0X0mhO4GiByaIw/mapv7xxgPOUAATso37gexhWT2aTjnIAHtopKmU1mWgVvaEr31kLVJRifpkjovl2SLtWthl9XQ7AilqN0lcaYllrlJXhk8/B5nQ9u3xw1EHIZQ/FQW4KS0xWjwa5YZMp6j7pp4R0f0hBX3ZhTM9x7AogiMta4DJAdIDeo0TycpSk/avWCbQJDgSJ6RSuxQhf/PdNMRnfLordadQP+bQwk/iFGmsSySdTRZB5K9F2PiCweRV630fOTm/6rZa+moEXxMUHkUDU9BvJ4Yg+k51//QtGQ/b/WnfIwgFX3T+n2/NSDBziHeGCvCOwNvGzItAydUNsG3OLBAVhG6PB7l63ckR4sbrV43Hz7w3YndKvXVoOIEMacD1W/qZSK0GtVvv9PG98zUPxV1XKI6jTwofh8t51lDlmY/kEFerILeTnslBA7bF/s9DgFM4aW/B58NwvHmCXh5v7WY1WRCNrtULhGJZHl1V/K9rJU=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mitchellkrog@gmail.com
    - TRAVIS_REPO_SLUG: mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites
    - GIT_BRANCH: master
    - TZ:       Africa/Johannesburg
    - PYFUNCEBLE_CONFIG_DIR: ${TRAVIS_BUILD_DIR}/.dev-tools/
    - PYFUNCEBLE_AUTO_CONFIGURATION: PyFunceble

jobs:
  fast_finish: true

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install domain2idna
  - pip3 install PyFunceble-dev
  - pip3 install ultimate-hosts-blacklist-whitelist
  #-

script:
  - bash .dev-tools/pre-deploy.sh

notifications:
  on_success:   change
  on_failure:   always
